# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11541a79c3831814a0bc813b3261ef5b26a887c5d5d430728f7aecf16dc5b5120fb3cb2b61e32e48c95354de0cd940a8c7191a587391262c253bd59b9e8c679e

test:
  secret_key_base: 456444aedf5405b2c659f51004bcba0106abb3e02d5ad7c396f3775eb8f21e23d80c1d2e1c8e0a965f8d6f2e9e59d6adc4cac2af6edf4c6b55dfe9fb8d374a37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
